all:
	gcc -o key-press-event `pkg-config --cflags --libs gtk+-2.0` key-press-event.c
	gcc -o key-press-event2 `pkg-config --cflags --libs gtk+-2.0` key-press-event2.c
	gcc -o key-press-event3 `pkg-config --cflags --libs gtk+-2.0` key-press-event3.c
	gcc -o key-press-event4 `pkg-config --cflags --libs gtk+-2.0` key-press-event4.c
	gcc -o key-press-event5 `pkg-config --cflags --libs gtk+-2.0` key-press-event5.c
	gcc -o combox `pkg-config --cflags --libs gtk+-2.0` combox.c
	gcc -o editbox `pkg-config --cflags --libs gtk+-2.0` editbox.c
	gcc -o editbox1 `pkg-config --cflags --libs gtk+-2.0` editbox1.c
	gcc -o key_snooper `pkg-config --cflags --libs gtk+-2.0` key_snooper.c
